#!/usr/bin/env python3
"""
TF-M Device Client Example
Simulates a TF-M device connecting to the cloud server
"""

import requests
import base64
import os
import json
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.backends import default_backend
import cbor2

SERVER_URL = "http://localhost:5000/api/v1"
DEVICE_ID = "test-tracker-001"

def generate_device_keys():
    """Generate device key pair"""
    print("Generating device keys...")

    private_key = ec.generate_private_key(ec.SECP256R1(), default_backend())
    public_key = private_key.public_key()

    # Export public key in PEM format
    public_pem = public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo
    )

    # Save keys
    with open('device_private_key.pem', 'wb') as f:
        f.write(private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption()
        ))

    with open('device_public_key.pem', 'wb') as f:
        f.write(public_pem)

    print("✓ Keys generated and saved")
    return private_key, public_pem.decode('utf-8')

def register_device(public_key_pem):
    """Register device with server"""
    print(f"\nRegistering device: {DEVICE_ID}")

    data = {
        "device_id": DEVICE_ID,
        "device_name": "Test Tracker",
        "manufacturer": "Test Corp",
        "model": "Tracker-v1",
        "hw_version": "1.0",
        "public_key": public_key_pem
    }

    response = requests.post(f"{SERVER_URL}/device/register", json=data)

    if response.status_code == 201:
        print("✓ Device registered successfully")
        return True
    elif response.status_code == 409:
        print("⚠ Device already registered")
        return True
    else:
        print(f"✗ Registration failed: {response.text}")
        return False

def create_mock_attestation_token(private_key, challenge):
    """
    Create a mock attestation token (simplified for testing)
    In real device, this would be generated by psa_initial_attest_get_token()
    """
    print("\nGenerating mock attestation token...")

    # Mock claims (PSA Initial Attestation)
    claims = {
        -75000: challenge,  # Nonce
        -75001: os.urandom(32),  # Instance ID (UEID)
        -75002: os.urandom(32),  # Boot seed
        -75003: "1.0.0",  # HW version
        -75004: os.urandom(32),  # Implementation ID
        -75005: [  # SW components
            {
                1: "BL2",  # Type
                2: os.urandom(32),  # Measurement
                4: "1.0.0",  # Version
                5: os.urandom(32),  # Signer ID
            },
            {
                1: "TF-M",
                2: os.urandom(32),
                4: "1.8.0",
                5: os.urandom(32),
            }
        ],
        -75006: "PSA_IOT_PROFILE_1",  # Profile
        -75007: 0x3000,  # Lifecycle (Secured)
    }

    # Encode payload
    payload = cbor2.dumps(claims)

    # Create protected headers
    protected = cbor2.dumps({
        1: -7  # Algorithm: ES256 (ECDSA with SHA-256)
    })

    # Create signature structure
    sig_structure = [
        "Signature1",
        protected,
        b'',  # external_aad
        payload
    ]
    sig_structure_bytes = cbor2.dumps(sig_structure)

    # Sign
    signature = private_key.sign(
        sig_structure_bytes,
        ec.ECDSA(hashes.SHA256())
    )

    # Create COSE_Sign1
    cose_sign1 = [
        protected,
        {},  # unprotected headers
        payload,
        signature
    ]

    token_bytes = cbor2.dumps(cose_sign1)

    print(f"✓ Token generated: {len(token_bytes)} bytes")
    return token_bytes

def perform_attestation(private_key):
    """Perform device attestation"""
    print("\n=== Attestation Flow ===")

    # Step 1: Get challenge
    print("1. Requesting challenge from server...")
    response = requests.get(f"{SERVER_URL}/device/{DEVICE_ID}/challenge")

    if response.status_code != 200:
        print(f"✗ Failed to get challenge: {response.text}")
        return False

    challenge_data = response.json()
    challenge = base64.b64decode(challenge_data['challenge'])
    print(f"✓ Received challenge: {challenge.hex()[:32]}...")

    # Step 2: Generate attestation token
    print("2. Generating attestation token...")
    token = create_mock_attestation_token(private_key, challenge)

    # Step 3: Send token for verification
    print("3. Sending token for verification...")
    attest_data = {
        "device_id": DEVICE_ID,
        "token": base64.b64encode(token).decode('utf-8'),
        "challenge": base64.b64encode(challenge).decode('utf-8')
    }

    response = requests.post(f"{SERVER_URL}/device/attest", json=attest_data)

    if response.status_code != 200:
        print(f"✗ Attestation failed: {response.text}")
        return False

    result = response.json()

    if result['verified']:
        print("✓ Attestation VERIFIED!")
        print("\nExtracted Claims:")
        for key, value in result['claims'].items():
            print(f"  {key}: {value}")
        return True
    else:
        print("✗ Attestation FAILED!")
        print(f"  Errors: {result.get('errors', [])}")
        return False

def submit_telemetry():
    """Submit sample telemetry data"""
    print("\n=== Submitting Telemetry ===")

    # GPS telemetry
    gps_data = {
        "type": "gps",
        "data": {
            "latitude": 37.7749,
            "longitude": -122.4194,
            "altitude": 100.5,
            "speed": 25.3,
            "satellites": 8,
            "timestamp": "2024-01-15T10:30:00Z"
        }
    }

    response = requests.post(f"{SERVER_URL}/device/{DEVICE_ID}/telemetry",
                             json=gps_data)

    if response.status_code == 200:
        print("✓ GPS telemetry submitted")
    else:
        print(f"✗ Failed to submit telemetry: {response.text}")

    # Sensor telemetry
    sensor_data = {
        "type": "sensor",
        "data": {
            "temperature": 22.5,
            "humidity": 45.0,
            "pressure": 1013.25,
            "battery": 87,
            "timestamp": "2024-01-15T10:30:00Z"
        }
    }

    response = requests.post(f"{SERVER_URL}/device/{DEVICE_ID}/telemetry",
                             json=sensor_data)

    if response.status_code == 200:
        print("✓ Sensor telemetry submitted")

def check_firmware_update():
    """Check for firmware updates"""
    print("\n=== Checking for Firmware Updates ===")

    response = requests.get(f"{SERVER_URL}/firmware/latest")

    if response.status_code == 200:
        firmware = response.json()
        print(f"Latest firmware: {firmware['version']}")
        print(f"  Size: {firmware['size']} bytes")
        print(f"  SHA256: {firmware['sha256']}")
        print(f"  Security Counter: {firmware['security_counter']}")
    elif response.status_code == 404:
        print("No firmware available")
    else:
        print(f"✗ Failed to check firmware: {response.text}")

def main():
    """Main entry point"""
    print("=" * 60)
    print(" TF-M Device Client Example")
    print("=" * 60)

    try:
        # Generate keys
        private_key, public_key_pem = generate_device_keys()

        # Copy public key to server certificates directory for verification
        print("\n⚠ IMPORTANT: Copy device_public_key.pem to server's certificates/ directory")
        print("   cp device_public_key.pem ../certificates/test-tracker-001.pem")
        input("\nPress ENTER after copying the key...")

        # Register device
        if not register_device(public_key_pem):
            print("\n✗ Failed to register device")
            return

        # Perform attestation
        if not perform_attestation(private_key):
            print("\n✗ Attestation failed")
            return

        # Submit telemetry
        submit_telemetry()

        # Check for updates
        check_firmware_update()

        print("\n" + "=" * 60)
        print("✓ Example completed successfully!")
        print("=" * 60)

    except requests.exceptions.ConnectionError:
        print("\n✗ Error: Could not connect to server")
        print("   Make sure the server is running: python tfm_cloud_server.py")
    except Exception as e:
        print(f"\n✗ Error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == '__main__':
    main()
